name: ThreadPlugin
version: '${project.version}'
main: com.ohdj.threadplugin.ThreadPlugin
api-version: '1.20'
author: [ ohdj ]
description: 测试Spigot插件的线程调用
commands:
  stuck:
    description: 执行同步或异步的线程任务
    usage: /<command> [1|2|3|...]