name: TabExecutorPlugin
version: '${project.version}'
main: com.ohdj.tabexecutorplugin.TabExecutorPlugin
api-version: '1.20'
authors: [ ohdj ]
description: 指令填充提示案例插件
commands:
  info:
    description: 指令填充提示案例插件