name: TextComponentPlugin
version: '${project.version}'
main: com.ohdj.textcomponentplugin.TextComponentPlugin
api-version: '1.20'
authors: [ ohdj ]
description: 测试聊天栏文本输入以及玩家的点击事件
commands:
  print-message:
    description: 展示ChatColor的两种常用用法
    usage: /print-message [1 | 2]
  print-title:
    description: 在玩家的屏幕中心展示一个标题和一个副标题
    usage: /print-title
  print-boss-bar:
    description: 展示BossBar的基本使用
    usage: /print-boss-bar
  print-text-component:
    description: 展示TextComponent的基本使用
    usage: /print-text-component
  print-component-builder:
    description: 展示ComponentBuilder的基本使用
    usage: /print-component-builder
  print-key-bind:
    description: 展示玩家按键绑定信息
    usage: /print-key-bind